version: '3.8'

services:
  api:
    container_name: teste_trabalho_engenharia_api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${TYPEORM_PORT_API}:${TYPEORM_PORT_API}
      - 9259:9259
    env_file:
      - .env
    networks:
      - docker-network
    depends_on:
      - db
  db:
    container_name: teste_trabalho_engenharia_db
    image: postgres:13-alpine
    
    networks:
      - docker-network
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    ports:
      - ${TYPEORM_PORT_DB_DOCKER}:${TYPEORM_PORT_DB}
    volumes:
      - api_db_data:/var/lib/postgresql/data
networks:
  docker-network:
volumes:
  api_db_data: